### ISSUE TITLE
Broken HTML block and browse preview doesn't work

### ISSUE THREAD

**Issue by cillianjoy** [Daniel-KM/Omeka-S-module-BlockPlus#6]
Recently upgraded to v3.1.2 and latest BlockPlus v3.3.14.2. Using centrerow. Turned off all modules except BlockPlus.
When I activate BlockPlus, content in existing HTML blocks is not visible, but it is still visible on the frontend saved webpage. See below

![image](https://user-images.githubusercontent.com/568928/161786605-f1826bb6-eb72-4554-9e98-dc0a92a6294f.png)

Also, the browse-preview-gallery doesn't work
![image](https://user-images.githubusercontent.com/568928/161786901-ce9ebd23-d784-4525-960c-31fd1a78704e.png)
![image](https://user-images.githubusercontent.com/568928/161787088-de546aae-2b3c-47e0-8ace-951d62fdd72d.png)

**Comment by mdavismcd** [comment]
Same thing here when the module is activated. The HTML block is greyed out, even when editing existing text in the block.

![image](https://user-images.githubusercontent.com/71394114/169598161-1e0803ca-6952-4e2e-b24d-84d6da37443b.png)

**Comment by Daniel-KM** [comment]
Thanks, this is fixed in version 3.3.15.

**Comment by mufticsanjin** [comment]
Hello, I have Omeka 3.2.1 and I Block Plus 3.4.15.6 and I still have the problem like mentioned above, where I can not edit HTML blocks, as they are greyed out. Adding a new HTML block results in no editable section.

<img width="870" alt="image" src="https://user-images.githubusercontent.com/50872373/214249683-e165bf77-4efa-4a0a-916c-96598738f346.png">

Should I wait for Omeka 4?

**Comment by Daniel-KM** [comment]
This is fixed in last versions, in Omeka S v3 and v4.

**Comment by saponidas** [comment]
Hi, the issue is present using Omeka S 4.04 and Block Plus 3.4.21 (PhP 8.0)
It seems that there is a conflict with the module Data Type RDF, since the html block loads fine when it is disabled.

Thanks in advance,

**Comment by saponidas** [comment]
Hi, the errror is related with the footnotes plugin (missing):

Browser Console shows:
_Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "footnotes" was not found_ 

I fixed it just downloading the plugin 
https://ckeditor.com/cke4/addon/footnotes

And putting the folder footnotes in the next Omeka S path:
`application/asset/vendor/ckeditor/plugins`

Hope this helps,

Best,

**Comment by mackenziekbrooks** [comment]
@saponidas Just wanted to say thanks for posting this fix, saved me some time!
